name: iris_ui
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  android_intent: ^2.0.2
  dartz: ^0.10.0
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_form_builder: ^6.0.1
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  freezed: ^0.14.5
  freezed_annotation: ^0.14.3
  injectable: ^1.5.0
  intl: ^0.17.0
  intl_utils: ^2.4.0
  logger: ^1.1.0
  pin_code_fields: ^7.3.0
  rxdart: ^0.27.1
  url_launcher: ^6.0.9
  annhub_flutter:
    # path: ../../packages/annhub_flutter
    git:
      url: git@github.com:ans-ari/annhub_flutter.git
      ref: main 
      path: packages/annhub_flutter
  tflite_flutter: ^0.9.0

dev_dependencies:
  build_runner: ^2.0.6
  flutter_lints: ^1.0.4
  injectable_generator: ^1.5.0

dependency_overrides:
  analyzer: ^2.1.0
  meta: ^1.7.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
